package com.picoder.sample.todolist.features.update

import android.app.AlertDialog
import android.os.Bundle
import android.view.*
import android.widget.Toast
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import com.picoder.sample.todolist.R
import com.picoder.sample.todolist.databinding.FragmentUpdateBinding
import com.picoder.sample.todolist.domain.entity.toIndex
import com.picoder.sample.todolist.domain.entity.toPriority
import com.picoder.sample.todolist.features.update.redux.UpdateToDoAction
import com.picoder.sample.todolist.features.update.redux.UpdateToDoNavigation
import com.picoder.sample.todolist.utils.setupListener
import com.picoder.sample.todolist.utils.showKeyboard
import dagger.hilt.android.AndroidEntryPoint


@AndroidEntryPoint
class UpdateFragment : Fragment() {

    private val viewModel: UpdateToDoViewModel by viewModels()

    private var _binding: FragmentUpdateBinding? = null

    private val binding get() = _binding!!

    // UpdateFragmentArgs is generated by safeargs
    private val args by navArgs<UpdateFragmentArgs>() // get argument data from navigation

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        // Inflate the layout for this fragment
        _binding = FragmentUpdateBinding.inflate(inflater)

        setHasOptionsMenu(true)

        binding.spinnerCurrentPriority.setupListener(requireContext())

        binding.edtCurrentTitle.requestFocus()

        binding.edtCurrentTitle.postDelayed({ showKeyboard(requireActivity()) }, 50)

        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        viewModel.state.observe(viewLifecycleOwner, { state ->
            binding.edtCurrentTitle.setText(state.updatedItem.title)
            binding.edtCurrentDescription.setText(state.updatedItem.description)
            binding.spinnerCurrentPriority.setSelection(state.updatedItem.priority.toIndex())

        })

        viewModel.nav.observe(viewLifecycleOwner, { nav ->
            when (nav) {
                is UpdateToDoNavigation.ShowMessageAndBackToList -> {
                    Toast.makeText(requireContext(), nav.message, Toast.LENGTH_LONG).show()
                    findNavController().navigate(R.id.action_updateFragment_to_listFragment)
                }

                is UpdateToDoNavigation.ShowErrorMessage -> Toast.makeText(
                    requireContext(),
                    nav.message,
                    Toast.LENGTH_LONG
                ).show()
            }
        })

        viewModel.doAction(UpdateToDoAction.OpenScreen(args.currentItem))
    }

    override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
        inflater.inflate(R.menu.update_fragment_menu, menu)
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        if (item.itemId == R.id.menu_save) {
            updateItem()
        } else if (item.itemId == R.id.menu_delete) {
            confirmItemRemoval()
        }
        return super.onOptionsItemSelected(item)
    }

    private fun confirmItemRemoval() {
        var builder = AlertDialog.Builder(requireContext())
        builder.setPositiveButton("Yes") { _, _ ->
            viewModel.doAction(UpdateToDoAction.DeleteToDoItem)
        }
        builder.setNegativeButton("No") { _, _ ->
            //
        }
        builder.setTitle("Delete '${args.currentItem.title}'?")
        builder.setMessage("Are you sure you want to delete '${args.currentItem.title}'?")
        builder.create().show()
    }

    private fun updateItem() {
        val title = binding.edtCurrentTitle.text.toString()
        val description = binding.edtCurrentDescription.text.toString()
        val priority = binding.spinnerCurrentPriority.selectedItem.toString()
        viewModel.doAction(
            UpdateToDoAction.UpdateToDoItem(
                title,
                priority.toPriority(),
                description
            )
        )
    }

    override fun onDestroy() {
        super.onDestroy()
        _binding = null
    }
}